version: '3'
services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode="no_engine_substitution"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nin
      MYSQL_USER: nin
      MYSQL_PASSWORD: nin
    ports:
      - "3307:3306"
  # cent_os+php+php-fpm+app本体
  lar:
    container_name: "lar"
    build: ./
    ports:
      - "86:80"
    volumes:
      - ./lar:/var/www/html
